name: dev-test

on: [push]

env:
  DOCKER_REGISTRY_URL: "docker.io"
  NAMESPACE: "cheche"
  APP_NAME: 'clash-dashboard'

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          export
          printenv

      - name: print event
        run: more /home/runner/work/_temp/_github_workflow/event.json
